#!/usr/bin/env bash

sudo apt install -y \
     software-properties-common\
     dirmngr \
     firefox-esr \
     firejail \
     direnv \
     gnutls-bin \
     rsync \
     apt-file \
     elpa-yasnippet-snippets \
     python3 \
     python3-dev \
     python3-venv \
     virtualenv \
     virtualenvwrapper \
     bbdb3 \
     gpg-agent \
     scdaemon \
     w3m

# configure GPG
mkdir -p ~/.gnupg/ 2> /dev/null
if ! grep 'enable-ssh-support' ~/.gnupg/gnupg.conf; then
    echo "enable-ssh-support" > ~/.gnupg/gnupg.conf
fi

data_dir="$(dirname $0)/data"
cp -v "${data_dir}"/gpg-agent* ~/.gnupg/
if ! grep gpg-agent-init.sh ~/.bashrc; then
    echo './gpg-agent-init.sh' > ~/.bashrc
fi

sudo systemctl --user --global enable \
     dirmngr.socket \
     gpg-agent.socket \
     gpg-agent-ssh.socket \
     gpg-agent-extra.socket

gpgconf --kill dirmngr
systemctl --user start dirmngr.socket

# install latest python3 pip
pushd $(mktemp -d)
wget https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py
pip --version
popd
