#!/usr/bin/env bash

set -euo pipefail

if [[ -d ~/.emacs.d ]]; then
   echo "error: remove ~/.emacs.d manually before executing this script"
   exit 1
fi

gh repo clone purcell/emacs.d ~/.emacs.d

# emacs configuration files
set -x
data_dir="$(dirname $0)/data"
pushd ${data_dir}
cp -v init-*.el ~/.emacs.d/lisp/
cp -v .signature .xface ~/.emacs.d/
cp -v .xface .signature ~/
popd

# modify the default init.el file in purcell's emacs.d
sed -i "s#(require 'init-org)#(require 'init-org-mode)#g" ~/.emacs.d/init.el
sed -i "s#(require 'init-python)#(require 'init-elpy)#g" ~/.emacs.d/init.el

# insert the following lines in ~/.emacs.d/init.el
# (require 'init-yasnippet)
# (require 'init-gnus)
# (require 'init-settings)
sed -i "s#(provide 'init)#(require 'init-yasnippet)\n(require 'init-gnus)\n(require 'init-settings)\n(light)\n(provide 'init)#g" \
    ~/.emacs.d/init.el

pushd ${data_dir}
cp -v authinfo[.gpg] ~/.authinfo.gpg
cp -v emacs.profile.firejail ~/.emacs.d/emacs.profile  # firejail profile for emacs
popd
